### PR TITLE
Replace boost with std

### LINKED ISSUE #812: Compilation error with boost::placeholders
## Description

Using `boost::placeholders` in 16.04 is not supported (out of the box).
Is there a reason why you use `boost::` and not `std::` ?

```
/root/gtsam/gtsam/inference/Symbol.cpp:66:61: error: 'boost::placeholders' has not been declared
   return boost::bind(&Symbol::chr, boost::bind(make, boost::placeholders::_1)) == c;
```

## Steps to reproduce

1. Compile in fresh 16.04 (docker ideally)

## Environment

Ubuntu 16.04

### PR DESCRIPTION
**Pull request by varunagrawal**
Fixes #812

1. Use `std::placeholders` instead of `boost::placeholders`.
2. Use `std::bind` instead of `boost::bind`.
3. Use `std::function` instead of `boost::function`.

Had to make edits to functionals in some places (used lambdas instead) to get things to work. Also the tests can't seem to disambiguate the placeholder variables (guess this is because some other boost library is importing `boost/bind` internally), so I just made them have the full namespace.

@ToniRV FYI

### CODE REVIEW

**Review by ProfFan — APPROVED** [review]
2nd

**Comment by dellaert** [comment]
Awesomesauce!
