### ISSUE TITLE
Unable to build GTSAM without Boost after latest update

### ISSUE THREAD

**Issue by Smithangshu** [borglab/gtsam#2058]
## Description

With the latest version whenever I am trying to build the library without `BOOST` in `Windows` with `CMake`, it fails. But in previous version. I could build it without any issue.

I am getting following error

`3>D:\Gits\gtsam\gtsam\base\Lie.h(316,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
3>(compiling source file '../../../gtsam/gtsam/precompiled_header.cpp')
3>D:\Gits\gtsam\gtsam\base\Lie.h(316,1):`

## Steps to reproduce

1. Just disable all the Boost related flags in CMake GUI.
2. Try to compile the build with VS 2022.

## Expected behavior

It should work without any issue.

## Environment
Windows 11.
VS 2022.
CMake GUI.

**Comment by ProfFan** [comment]
Could be #2047

**Comment by dellaert** [comment]
@Smithangshu could you try with #2047 undone?

**Comment by Smithangshu** [comment]
@ProfFan yes, it is the cause.

**Comment by Smithangshu** [comment]
@dellaert if I comment out this section from Lie.h. And build it, then it works like charm.

![Image](https://github.com/user-attachments/assets/c8302302-af16-4214-b734-777c2b42e88c)

**Comment by dellaert** [comment]
Ah, that’s my bad! It should now use the new macro. It was my Hat/Vee that probably landed concurrently with @varunagrawal ‘s PR

**Comment by ProfFan** [comment]
Should be solved with #2060
